### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by bergwerf** [CENTURY-Tech/input-math#1]
Can you add a license to your project? I want to use your TypeScript definition of MathQuill. Thanks!

**Comment by relvao** [comment]
We had defined MIT in the bower.json file. I'll add the MIT licence as a LICENCE file later today, for clarity.
https://github.com/CENTURY-Tech/input-math/blob/master/bower.json

**Comment by iainjreid** [comment]
License added and can be found here: https://github.com/CENTURY-Tech/input-math/blob/master/LICENSE
